# Generated by Django 4.2.5 on 2023-10-24 11:50

import api.models.file
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'file_groups',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('local_ip', models.GenericIPAddressField(unique=True)),
                ('api_port', models.PositiveIntegerField(default=14000)),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('max_replicas', models.IntegerField(blank=True, null=True)),
                ('directory', models.CharField()),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Replication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate', models.BooleanField(default=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replications', to='api.node')),
                ('sources', models.ManyToManyField(blank=True, related_name='replications', to='api.source')),
            ],
            options={
                'db_table': 'replications',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('H:/projects/replicator/data')), upload_to=api.models.file.get_save_path)),
                ('path', models.CharField()),
                ('created_at', models.DateTimeField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.filegroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.source')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
