# Generated by Django 4.2.5 on 2023-10-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replication',
            unique_together={('node', 'source')},
        ),
    ]
