# Generated by Django 4.2.5 on 2023-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_replication_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(models.F('path'), name='path_idx'),
        ),
    ]
